In [1]:
import ipywidgets

import numpy as np
import bqplot

## Example of using bqplot with imperative (non-matplotlib-like interface)

**Step 1:** Getting data together (starting with random data)

In [2]:
x = np.arange(100)

In [6]:
#x

In [4]:
y = np.random.random(100)

In [7]:
#y

**Step 2**: Scales -- linear in this case (mapping the data to a visual representation/encoding), encoding in this case will be distance along x/y axis

In [8]:
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

In [9]:
x_sc

LinearScale()

**Step 3**: Axis (could be marks)

In [10]:
ax_x = bqplot.Axis(scale = x_sc, label='X value')
ax_y = bqplot.Axis(scale = y_sc, label='Y value', orientation='vertical')

In [11]:
bqplot.Axis?

**Step 4**: Marks (in our case, a line mark to make a line plot)

In [12]:
lines = bqplot.Lines(x=x, y = y, scales={'x':x_sc, 'y':y_sc})

In [14]:
#lines

*Sometimes here would be interactions, but not yet!*

**Finally**: All together as a figure

In [15]:
fig = bqplot.Figure(marks=[lines], axes=[ax_x, ax_y])

In [18]:
#display(fig)
fig

Figure(axes=[Axis(label='X value', scale=LinearScale(), side='bottom'), Axis(label='Y value', orientation='ver…

Let's add in some interactivity using `bqplot.interacts`

In [19]:
pz = bqplot.interacts.PanZoom(scales={'x':[x_sc], 'y':[y_sc]})

In [20]:
pz

PanZoom(scales={'x': [LinearScale()], 'y': [LinearScale()]})

Re-build figure object and include interactivity:

In [21]:
fig = bqplot.Figure(marks=[lines], axes=[ax_x, ax_y], interaction=pz)

In [22]:
fig

Figure(axes=[Axis(label='X value', scale=LinearScale(), side='bottom'), Axis(label='Y value', orientation='ver…

## Try another one: Random Scatter plot

In [23]:
# 1. Data
x = np.random.random(100) # random x
y = np.random.random(100) # random y

In [25]:
#x, y

In [26]:
# 2. scales
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

# 3. axis
x_ax = bqplot.Axis(scale = x_sc, label = 'Random X')
y_ax = bqplot.Axis(scale = y_sc, label = 'Random Y', orientation = 'vertical')

In [27]:
# 4. Marks
scatters = bqplot.Scatter(x=x, y = y, scales = {'x':x_sc, 'y':y_sc})

In [31]:
# 5. interactions... stay tuned!
# trying another one out -- fast interval selector
selector = bqplot.interacts.FastIntervalSelector(scale=x_sc, marks=[scatters])

In [32]:
fig = bqplot.Figure(marks=[scatters], axes=[x_ax, y_ax], interaction=selector)
fig

Figure(axes=[Axis(label='Random X', scale=LinearScale(), side='bottom'), Axis(label='Random Y', orientation='v…

In [33]:
selector.keys

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'color',
 'marks',
 'scale',
 'selected',
 'size']

the `selector.marks` is the same as our `scatters` marks

In [36]:
#selector.marks

In [37]:
#scatters

In [39]:
selector.selected

array([0.50055503, 0.98524619])

Looking forward -- we can maybe use this range to "subset" our data and do something else with the selected subset... (more on this later)

In [41]:
scatters.keys

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'apply_clip',
 'color',
 'colors',
 'default_size',
 'default_skew',
 'display_legend',
 'display_names',
 'drag_color',
 'drag_size',
 'enable_delete',
 'enable_hover',
 'enable_move',
 'fill',
 'hovered_point',
 'hovered_style',
 'interactions',
 'label_display_horizontal_offset',
 'label_display_vertical_offset',
 'labels',
 'marker',
 'names',
 'names_unique',
 'opacities',
 'opacity',
 'preserve_domain',
 'restrict_x',
 'restrict_y',
 'rotation',
 'scales',
 'scales_metadata',
 'selected',
 'selected_style',
 'size',
 'skew',
 'stroke',
 'stroke_width',
 'tooltip',
 'tooltip_location',
 'tooltip_style',
 'unhovered_style',
 'unselected_style',
 'update_on_move',
 'visible',
 'x',
 'y']

Highlighting selected and unselected objects in our plot:

In [45]:
scatters.unselected_style = {'opacity': 0.8} # make unselected points a little see-through

scatters.selected_style = {'fill':'red', 'stroke':'yellow'} # fill dots with red, make stroke around yellow
# CSS stylings -- this will look familar!

In [46]:
fig = bqplot.Figure(marks=[scatters],axes=[x_ax, y_ax], interaction=selector)

In [47]:
fig

Figure(axes=[Axis(label='Random X', scale=LinearScale(), side='bottom'), Axis(label='Random Y', orientation='v…

For reference: https://bqplot.readthedocs.io/en/latest/

## Random Heatmap in 2D

In [50]:
# 1. data
data = np.random.random((10,10)) # 10x10 array of random data

In [54]:
data[0,0], data[1,0]

(0.1256531563733807, 0.3055935772536119)

In [55]:
# 2. scales -- for this data it will be a color scale
col_sc = bqplot.ColorScale()

# 3. Axis -- color axis ... skip for now!

# 4. Mark -- a color-scale like mark
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

# 5. Interactions ... skip for now!

# figure!
fig = bqplot.Figure(marks=[heat_map])
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.12565…

In [57]:
# 1. data -- same as before, so not changing

# 2. scales -- for this data it will be a color scale
col_sc = bqplot.ColorScale(scheme="Blues")

# 3. Axis -- color axis ... skip for now!

# 4. Mark -- a color-scale like mark
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

# 5. Interactions ... skip for now!

# figure!
fig = bqplot.Figure(marks=[heat_map])
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.12565…

In [61]:
# 1. data -- same as before, so not changing

# 2. scales -- for this data it will be a color scale
col_sc = bqplot.ColorScale(scheme="Blues")

# 3. Axis -- color axis means colorbar
c_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')

# 4. Mark -- a color-scale like mark
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

# 5. Interactions ... skip for now!

# figure!
fig = bqplot.Figure(marks=[heat_map], axes=[c_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Blues'), side='right')], fig_margin={'…

In [64]:
# 1. data -- same as before, so not changing

# 2. scales
# 2.1 color scale
col_sc = bqplot.ColorScale(scheme="Blues")
# 2.2 x/y scales
x_sc = bqplot.OrdinalScale() # for categorical data
y_sc = bqplot.OrdinalScale()

# 3. Axis
# 3.1 color axis means colorbar
c_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
# 3.2 x/y axis
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- a color-scale like mark
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc})

# 5. Interactions ... skip for now!

# figure!
fig = bqplot.Figure(marks=[heat_map], axes=[c_ax, y_ax, x_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Blues'), side='right'), Axis(orientati…

In [65]:
# 1. data -- same as before, so not changing

# 2. scales
# 2.1 color scale
col_sc = bqplot.ColorScale(scheme="Blues")
# 2.2 x/y scales
x_sc = bqplot.OrdinalScale() # for categorical data
y_sc = bqplot.OrdinalScale()

# 3. Axis
# 3.1 color axis means colorbar
c_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
# 3.2 x/y axis
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- a color-scale like mark
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'}, # if I click on a bin, select the bin
                             anchor_style={'fill':'red'}, # to highlight our selection as red
                             selected_style={'opacity':1.0}, # totally opaque if selected
                             unselected_style={'opacity':0.8}) # a little see-through if not selected

# 5. Interactions ... first adding in to the "marks" call above

# figure!
fig = bqplot.Figure(marks=[heat_map], axes=[c_ax, y_ax, x_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Blues'), side='right'), Axis(orientati…

In [67]:
heat_map.selected # the *trait* of x/y indicies of the heatmap gets updated

array([[5, 5]])

In [68]:
def on_selected(change):
    print(change)

In [70]:
# 1. data -- same as before, so not changing

# 2. scales
# 2.1 color scale
col_sc = bqplot.ColorScale(scheme="Blues")
# 2.2 x/y scales
x_sc = bqplot.OrdinalScale() # for categorical data
y_sc = bqplot.OrdinalScale()

# 3. Axis
# 3.1 color axis means colorbar
c_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
# 3.2 x/y axis
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- a color-scale like mark
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'}, # if I click on a bin, select the bin
                             anchor_style={'fill':'red'}, # to highlight our selection as red
                             selected_style={'opacity':1.0}, # totally opaque if selected
                             unselected_style={'opacity':0.8}) # a little see-through if not selected

# 5. Interactions ... first adding in to the "marks" call above, and than adding an observation function
heat_map.observe(on_selected, 'selected')


# figure!
fig = bqplot.Figure(marks=[heat_map], axes=[c_ax, y_ax, x_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Blues'), side='right'), Axis(orientati…

{'name': 'selected', 'old': None, 'new': array([[0, 0]]), 'owner': GridHeatMap(anchor_style={'fill': 'red'}, color=array([[0.12565316, 0.01699575, 0.59763266, 0.58898817, 0.66850296,
        0.47986429, 0.1077714 , 0.59449319, 0.26555982, 0.80915522],
       [0.30559358, 0.33934277, 0.4411446 , 0.78538223, 0.72149264,
        0.3706186 , 0.10933616, 0.18034364, 0.07074292, 0.48699548],
       [0.64625221, 0.9111042 , 0.49868474, 0.78496956, 0.24842065,
        0.34912409, 0.02115065, 0.2689668 , 0.95541326, 0.70885887],
       [0.96929384, 0.21995646, 0.22893606, 0.32675555, 0.94560838,
        0.29160461, 0.17702611, 0.52413342, 0.35603856, 0.8841929 ],
       [0.92561768, 0.70184848, 0.78569794, 0.82582146, 0.39759195,
        0.2729544 , 0.27571207, 0.02093082, 0.85624401, 0.46386196],
       [0.19136529, 0.82109875, 0.80469364, 0.54854961, 0.87839152,
        0.78843036, 0.15995364, 0.81255544, 0.86509626, 0.04168094],
       [0.60875626, 0.41466904, 0.42920237, 0.47794754, 0.52789

In [71]:
def on_selected(change):
    print(change['owner'])

In [72]:
# 1. data -- same as before, so not changing

# 2. scales
# 2.1 color scale
col_sc = bqplot.ColorScale(scheme="Blues")
# 2.2 x/y scales
x_sc = bqplot.OrdinalScale() # for categorical data
y_sc = bqplot.OrdinalScale()

# 3. Axis
# 3.1 color axis means colorbar
c_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
# 3.2 x/y axis
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- a color-scale like mark
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'}, # if I click on a bin, select the bin
                             anchor_style={'fill':'red'}, # to highlight our selection as red
                             selected_style={'opacity':1.0}, # totally opaque if selected
                             unselected_style={'opacity':0.8}) # a little see-through if not selected

# 5. Interactions ... first adding in to the "marks" call above, and than adding an observation function
heat_map.observe(on_selected, 'selected')


# figure!
fig = bqplot.Figure(marks=[heat_map], axes=[c_ax, y_ax, x_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Blues'), side='right'), Axis(orientati…

GridHeatMap(anchor_style={'fill': 'red'}, color=array([[0.12565316, 0.01699575, 0.59763266, 0.58898817, 0.66850296,
        0.47986429, 0.1077714 , 0.59449319, 0.26555982, 0.80915522],
       [0.30559358, 0.33934277, 0.4411446 , 0.78538223, 0.72149264,
        0.3706186 , 0.10933616, 0.18034364, 0.07074292, 0.48699548],
       [0.64625221, 0.9111042 , 0.49868474, 0.78496956, 0.24842065,
        0.34912409, 0.02115065, 0.2689668 , 0.95541326, 0.70885887],
       [0.96929384, 0.21995646, 0.22893606, 0.32675555, 0.94560838,
        0.29160461, 0.17702611, 0.52413342, 0.35603856, 0.8841929 ],
       [0.92561768, 0.70184848, 0.78569794, 0.82582146, 0.39759195,
        0.2729544 , 0.27571207, 0.02093082, 0.85624401, 0.46386196],
       [0.19136529, 0.82109875, 0.80469364, 0.54854961, 0.87839152,
        0.78843036, 0.15995364, 0.81255544, 0.86509626, 0.04168094],
       [0.60875626, 0.41466904, 0.42920237, 0.47794754, 0.52789316,
        0.95475338, 0.37604309, 0.12409343, 0.21642193, 0.9092

In [73]:
def on_selected(change):
    print(change['owner'].selected)

In [74]:
# 1. data -- same as before, so not changing

# 2. scales
# 2.1 color scale
col_sc = bqplot.ColorScale(scheme="Blues")
# 2.2 x/y scales
x_sc = bqplot.OrdinalScale() # for categorical data
y_sc = bqplot.OrdinalScale()

# 3. Axis
# 3.1 color axis means colorbar
c_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
# 3.2 x/y axis
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- a color-scale like mark
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'}, # if I click on a bin, select the bin
                             anchor_style={'fill':'red'}, # to highlight our selection as red
                             selected_style={'opacity':1.0}, # totally opaque if selected
                             unselected_style={'opacity':0.8}) # a little see-through if not selected

# 5. Interactions ... first adding in to the "marks" call above, and than adding an observation function
heat_map.observe(on_selected, 'selected')


# figure!
fig = bqplot.Figure(marks=[heat_map], axes=[c_ax, y_ax, x_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Blues'), side='right'), Axis(orientati…

[[0 0]]
[[0 1]]
[[2 1]]
[[4 2]]
[[3 3]]
[[2 5]]
[[0 4]]
[[5 4]]
[[4 6]]
[[2 6]]
[[1 6]
 [2 6]]
[[1 7]
 [1 6]
 [2 6]
 [2 7]]
[[1 8]
 [1 6]
 [1 7]
 [2 6]
 [2 7]
 [2 8]]
[[3 8]
 [2 6]
 [2 7]
 [2 8]
 [3 6]
 [3 7]]


In [75]:
# we only want to enable the selection of 1 cell (a choice!)
def on_selected(change):
    if len(change['owner'].selected) == 1:
        print(change['owner'].selected[0]) # just print the one and only element

In [76]:
# 1. data -- same as before, so not changing

# 2. scales
# 2.1 color scale
col_sc = bqplot.ColorScale(scheme="Blues")
# 2.2 x/y scales
x_sc = bqplot.OrdinalScale() # for categorical data
y_sc = bqplot.OrdinalScale()

# 3. Axis
# 3.1 color axis means colorbar
c_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
# 3.2 x/y axis
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- a color-scale like mark
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'}, # if I click on a bin, select the bin
                             anchor_style={'fill':'red'}, # to highlight our selection as red
                             selected_style={'opacity':1.0}, # totally opaque if selected
                             unselected_style={'opacity':0.8}) # a little see-through if not selected

# 5. Interactions ... first adding in to the "marks" call above, and than adding an observation function
heat_map.observe(on_selected, 'selected')


# figure!
fig = bqplot.Figure(marks=[heat_map], axes=[c_ax, y_ax, x_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Blues'), side='right'), Axis(orientati…

[4 5]
[3 5]
[2 2]
[3 1]
[2 2]
[3 2]
[3 5]
[1 5]
[0 6]
[2 3]


In [77]:
# use ipywidgets to make a label that will (eventually!) be updated with the data values of the selection
mySelectedLabel = ipywidgets.Label()
mySelectedLabel.value = 'STUFF'

In [78]:
mySelectedLabel

Label(value='STUFF')

In [79]:
# 1. data -- same as before, so not changing

# 2. scales
# 2.1 color scale
col_sc = bqplot.ColorScale(scheme="Blues")
# 2.2 x/y scales
x_sc = bqplot.OrdinalScale() # for categorical data
y_sc = bqplot.OrdinalScale()

# 3. Axis
# 3.1 color axis means colorbar
c_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
# 3.2 x/y axis
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- a color-scale like mark
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'}, # if I click on a bin, select the bin
                             anchor_style={'fill':'red'}, # to highlight our selection as red
                             selected_style={'opacity':1.0}, # totally opaque if selected
                             unselected_style={'opacity':0.8}) # a little see-through if not selected

# 5. Interactions ... first adding in to the "marks" call above, and than adding an observation function
heat_map.observe(on_selected, 'selected')


# figure!
fig = bqplot.Figure(marks=[heat_map], axes=[c_ax, y_ax, x_ax])
#fig

# put the label widget ontop of this figure object
myDashboard = ipywidgets.VBox([mySelectedLabel, fig])
myDashboard

[4 3]
[3 2]
[3 4]


In [80]:
# we only want to enable the selection of 1 cell (a choice!)
def on_selected(change):
    if len(change['owner'].selected) == 1:
        #print(change['owner'].selected[0]) # just print the one and only element
        i,j = change['owner'].selected[0]
        v = data[i,j] # grabbing the data value at the i,j'th bin of our 2D array
        mySelectedLabel.value = 'Data Value = ' + str(v) # set the value of our label widget

In [81]:
# 1. data -- same as before, so not changing

# 2. scales
# 2.1 color scale
col_sc = bqplot.ColorScale(scheme="Blues")
# 2.2 x/y scales
x_sc = bqplot.OrdinalScale() # for categorical data
y_sc = bqplot.OrdinalScale()

# 3. Axis
# 3.1 color axis means colorbar
c_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
# 3.2 x/y axis
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- a color-scale like mark
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'}, # if I click on a bin, select the bin
                             anchor_style={'fill':'red'}, # to highlight our selection as red
                             selected_style={'opacity':1.0}, # totally opaque if selected
                             unselected_style={'opacity':0.8}) # a little see-through if not selected

# 5. Interactions ... first adding in to the "marks" call above, and than adding an observation function
heat_map.observe(on_selected, 'selected')


# figure!
fig = bqplot.Figure(marks=[heat_map], axes=[c_ax, y_ax, x_ax])
#fig

# put the label widget ontop of this figure object
myDashboard = ipywidgets.VBox([mySelectedLabel, fig])
myDashboard

In [83]:
i,j = 5,6
data[i,j]

0.15995364311257487

## Random heatmap + Histogram with 3D data

In [84]:
data = np.random.random( (10,10, 20))

In [86]:
data[0,0]

array([0.61690295, 0.45515413, 0.34901103, 0.2578603 , 0.96139683,
       0.07407992, 0.55435487, 0.14187451, 0.68320865, 0.57410938,
       0.17659493, 0.20353913, 0.01839286, 0.52636845, 0.52961607,
       0.16555877, 0.2641423 , 0.35146693, 0.2582152 , 0.80623643])

In [90]:
data[0,0].sum()

7.968083640349025

In [87]:
data.shape

(10, 10, 20)

In [88]:
np.sum(data,axis=2)

array([[ 7.96808364,  8.89300021,  9.0847448 , 12.4995781 ,  8.99302509,
        11.85078076,  9.95255104, 11.70187849,  8.85398641, 10.7425926 ],
       [ 8.90242724, 12.14947535,  9.44727265, 12.23270648, 10.07327186,
         8.31315868,  9.35269841, 11.56577862, 10.48265126,  7.62799518],
       [ 8.28042946, 11.89613529, 11.44315702, 11.46648641,  8.98567283,
        11.34080846,  8.97085326,  9.33222064, 12.74284632,  9.35943536],
       [ 7.31791808,  9.4121305 ,  7.08018527, 10.30835917, 12.93584251,
         9.95557275,  9.29829807,  9.90368984, 11.04076255,  8.43438095],
       [ 9.07456128, 13.83018896,  9.17478273, 10.98282067,  9.0851357 ,
        11.36610463, 10.90974189, 10.81902157, 10.38917061,  9.85153729],
       [14.29986207, 11.25214068, 11.33212539,  7.17496497,  9.3249139 ,
        11.05683844, 11.27727515, 10.23681288,  9.46222647,  9.05417321],
       [11.9580918 ,  8.64267908, 10.9724112 ,  8.68959579,  8.50999412,
        12.52299302, 11.60332729,  8.01102483

In [89]:
np.sum(data,axis=2).shape

(10, 10)

In [91]:
# we only want to enable the selection of 1 cell (a choice!)
def on_selected(change):
    if len(change['owner'].selected) == 1:
        #print(change['owner'].selected[0]) # just print the one and only element
        i,j = change['owner'].selected[0]
        v = data[i,j].sum() # FOR 3D ARRAY SUM ALONG 3rd AXIS!!
        mySelectedLabel.value = 'Data Value = ' + str(v) # set the value of our label widget

In [92]:
# 1. data -- same as before, so not changing

# 2. scales
# 2.1 color scale
col_sc = bqplot.ColorScale(scheme="Blues")
# 2.2 x/y scales
x_sc = bqplot.OrdinalScale() # for categorical data
y_sc = bqplot.OrdinalScale()

# 3. Axis
# 3.1 color axis means colorbar
c_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
# 3.2 x/y axis
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- a color-scale like mark
heat_map = bqplot.GridHeatMap(color=np.sum(data,axis=2), ## HAVE CHANGED THIS TOO!!
                              scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'}, # if I click on a bin, select the bin
                             anchor_style={'fill':'red'}, # to highlight our selection as red
                             selected_style={'opacity':1.0}, # totally opaque if selected
                             unselected_style={'opacity':0.8}) # a little see-through if not selected

# 5. Interactions ... first adding in to the "marks" call above, and than adding an observation function
heat_map.observe(on_selected, 'selected')


# figure!
fig = bqplot.Figure(marks=[heat_map], axes=[c_ax, y_ax, x_ax])
#fig

# put the label widget ontop of this figure object
myDashboard = ipywidgets.VBox([mySelectedLabel, fig])
myDashboard

We want to be able to show a representation of this data along its 3rd axis.

In [98]:
i,j=5,5

In [99]:
data[i,j]

array([0.84203136, 0.18722986, 0.74975898, 0.54488063, 0.32476422,
       0.59061688, 0.87258981, 0.60132667, 0.64461424, 0.56958333,
       0.77645376, 0.67841557, 0.57529343, 0.00511034, 0.59422291,
       0.80836708, 0.05964464, 0.99255965, 0.22285889, 0.41651618])

One thing we might want to know, is what is the distribution of these data values along a selected i/j bin.

Stragedy: First start with making a histogram with a "hard-coded" i/j combination and THEN think about how to link it to the grid heatmap.

In [100]:
# 1. data - data[i,j] where i,j are hardcoded to 0,0 above

# 2. Scales
x_sch = bqplot.LinearScale()
y_sch = bqplot.LinearScale()

# 3. Axis
x_axh = bqplot.Axis(scale=x_sch, label='Values along 3rd Axis of data')
y_axh = bqplot.Axis(scale=y_sch, label='Frequency', orientation='vertical')

# 4. Marks
hist = bqplot.Hist(sample=data[i,j], normalized=False, # counts in each bin
                  scales={'sample':x_sch, 'count':y_sch}, bins=5)

# Put it all together into a figure
figh = bqplot.Figure(marks=[hist], axes=[x_axh, y_axh])
figh

Figure(axes=[Axis(label='Values along 3rd Axis of data', scale=LinearScale()), Axis(label='Frequency', orienta…

In [96]:
bqplot.Hist?

In [101]:
hist.keys

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'apply_clip',
 'bins',
 'colors',
 'count',
 'display_legend',
 'enable_hover',
 'interactions',
 'labels',
 'midpoints',
 'normalized',
 'opacities',
 'preserve_domain',
 'sample',
 'scales',
 'scales_metadata',
 'selected',
 'selected_style',
 'stroke',
 'tooltip',
 'tooltip_location',
 'tooltip_style',
 'unselected_style',
 'visible']

In [102]:
hist.sample

array([0.84203136, 0.18722986, 0.74975898, 0.54488063, 0.32476422,
       0.59061688, 0.87258981, 0.60132667, 0.64461424, 0.56958333,
       0.77645376, 0.67841557, 0.57529343, 0.00511034, 0.59422291,
       0.80836708, 0.05964464, 0.99255965, 0.22285889, 0.41651618])

We are going to update our observation function so that the `hist.sample` of our marks updates as well when we select something.

In [103]:
# we only want to enable the selection of 1 cell (a choice!)
def on_selected(change):
    if len(change['owner'].selected) == 1:
        #print(change['owner'].selected[0]) # just print the one and only element
        i,j = change['owner'].selected[0]
        v = data[i,j].sum() # FOR 3D ARRAY SUM ALONG 3rd AXIS!!
        mySelectedLabel.value = 'Data Value = ' + str(v) # set the value of our label widget
        ##### ADDING IN UPDATE FOR HISTOGRAM ####
        hist.sample = data[i,j]

In [104]:
# 1. data -- same as before, so not changing

# 2. scales
# 2.1 color scale
col_sc = bqplot.ColorScale(scheme="Blues")
# 2.2 x/y scales
x_sc = bqplot.OrdinalScale() # for categorical data
y_sc = bqplot.OrdinalScale()

# 3. Axis
# 3.1 color axis means colorbar
c_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
# 3.2 x/y axis
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- a color-scale like mark
heat_map = bqplot.GridHeatMap(color=np.sum(data,axis=2), ## HAVE CHANGED THIS TOO!!
                              scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'}, # if I click on a bin, select the bin
                             anchor_style={'fill':'red'}, # to highlight our selection as red
                             selected_style={'opacity':1.0}, # totally opaque if selected
                             unselected_style={'opacity':0.8}) # a little see-through if not selected

# 5. Interactions ... first adding in to the "marks" call above, and than adding an observation function
heat_map.observe(on_selected, 'selected')


# figure!
fig = bqplot.Figure(marks=[heat_map], axes=[c_ax, y_ax, x_ax])
#fig

# put the label widget ontop of this figure object
myDashboard = ipywidgets.VBox([mySelectedLabel, fig])
myDashboard

Do more complex layout stuff:

In [106]:
figures = ipywidgets.HBox([fig, figh]) # figures side by side in order: heat map, histogram

myDashboard = ipywidgets.VBox([mySelectedLabel, figures])
myDashboard

In [107]:
# further mess with the display of this data
fig.layout.min_width='400px'
figh.layout.min_width='400px'

Adding one more option:

In [108]:
hist.keys

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'apply_clip',
 'bins',
 'colors',
 'count',
 'display_legend',
 'enable_hover',
 'interactions',
 'labels',
 'midpoints',
 'normalized',
 'opacities',
 'preserve_domain',
 'sample',
 'scales',
 'scales_metadata',
 'selected',
 'selected_style',
 'stroke',
 'tooltip',
 'tooltip_location',
 'tooltip_style',
 'unselected_style',
 'visible']

In [109]:
hist.bins

5

Make a bin widget to change the number of bins of our histogram:

In [110]:
bins_slider = ipywidgets.IntSlider(value=5, min=1, max=data.shape[2])

In [111]:
bins_slider

IntSlider(value=5, max=20, min=1)

We'll use `jslink` to link the TRAIT of hist of bins (`hist.bins`) to updates in this slider's value:

In [112]:
ipywidgets.jslink((bins_slider,'value'), (hist,'bins'))

Link(source=(IntSlider(value=14, max=20, min=1), 'value'), target=(Hist(bins=5, colors=['steelblue'], count=ar…

Re-build dashboard so that I've got everything in one place:

In [113]:
figures = ipywidgets.HBox([fig,figh])

controls_etc = ipywidgets.HBox([mySelectedLabel, bins_slider])

myDashboard = ipywidgets.VBox([controls_etc, figures])
myDashboard

Tip: if something isn't working, try remaking and re-linking everything!

In [122]:
mySelectedLabel = ipywidgets.Label()
mySelectedLabel.value = 'STUFF'

In [123]:
# 1. data - data[i,j] where i,j are hardcoded to 0,0 above

# 2. Scales
x_sch = bqplot.LinearScale()
y_sch = bqplot.LinearScale()

# 3. Axis
x_axh = bqplot.Axis(scale=x_sch, label='Values along 3rd Axis of data')
y_axh = bqplot.Axis(scale=y_sch, label='Frequency', orientation='vertical')

# 4. Marks
hist = bqplot.Hist(sample=data[i,j], normalized=False, # counts in each bin
                  scales={'sample':x_sch, 'count':y_sch}, bins=5)

# Put it all together into a figure
figh = bqplot.Figure(marks=[hist], axes=[x_axh, y_axh])

In [124]:
# we only want to enable the selection of 1 cell (a choice!)
def on_selected(change):
    if len(change['owner'].selected) == 1:
        #print(change['owner'].selected[0]) # just print the one and only element
        i,j = change['owner'].selected[0]
        v = data[i,j].sum() # FOR 3D ARRAY SUM ALONG 3rd AXIS!!
        mySelectedLabel.value = 'Data Value = ' + str(v) # set the value of our label widget
        ##### ADDING IN UPDATE FOR HISTOGRAM ####
        hist.sample = data[i,j]

In [125]:
# 1. data -- same as before, so not changing

# 2. scales
# 2.1 color scale
col_sc = bqplot.ColorScale(scheme="Blues")
# 2.2 x/y scales
x_sc = bqplot.OrdinalScale() # for categorical data
y_sc = bqplot.OrdinalScale()

# 3. Axis
# 3.1 color axis means colorbar
c_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
# 3.2 x/y axis
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark -- a color-scale like mark
heat_map = bqplot.GridHeatMap(color=np.sum(data,axis=2), ## HAVE CHANGED THIS TOO!!
                              scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'}, # if I click on a bin, select the bin
                             anchor_style={'fill':'red'}, # to highlight our selection as red
                             selected_style={'opacity':1.0}, # totally opaque if selected
                             unselected_style={'opacity':0.8}) # a little see-through if not selected

# 5. Interactions ... first adding in to the "marks" call above, and than adding an observation function
heat_map.observe(on_selected, 'selected')


# figure!
fig = bqplot.Figure(marks=[heat_map], axes=[c_ax, y_ax, x_ax])

In [126]:
bins_slider = ipywidgets.IntSlider(value=5, min=1, max=data.shape[2])

In [127]:
ipywidgets.jslink((bins_slider,'value'), (hist,'bins'))

Link(source=(IntSlider(value=5, max=20, min=1), 'value'), target=(Hist(bins=5, colors=['steelblue'], count=arr…

In [128]:
figures = ipywidgets.HBox([fig,figh])

controls_etc = ipywidgets.HBox([mySelectedLabel, bins_slider])

myDashboard = ipywidgets.VBox([controls_etc, figures])
myDashboard