In [1]:
import bqplot
import numpy as np
import ipywidgets

## 1. Random Line plot

In [2]:
# 1. Data
x = np.arange(100)

In [3]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [4]:
y = np.random.random(100)

In [5]:
y

array([0.46122347, 0.44151456, 0.1111893 , 0.62253545, 0.32716589,
       0.03439785, 0.66088521, 0.46552615, 0.99963127, 0.87534873,
       0.07755301, 0.38566262, 0.01930129, 0.08676906, 0.17311304,
       0.83492398, 0.89613075, 0.71905952, 0.39212283, 0.57567524,
       0.02493849, 0.60386435, 0.70610624, 0.18688038, 0.5498312 ,
       0.53357392, 0.44587048, 0.74272883, 0.59682042, 0.60218623,
       0.81615802, 0.24803489, 0.14918757, 0.60753268, 0.38431671,
       0.93763148, 0.33292647, 0.81747029, 0.88141489, 0.89628229,
       0.20950579, 0.60870209, 0.31660486, 0.54220475, 0.85552366,
       0.97634819, 0.65067141, 0.53666175, 0.13934266, 0.68185179,
       0.93645056, 0.67069007, 0.49800841, 0.9921424 , 0.6539567 ,
       0.80144463, 0.44168627, 0.10597509, 0.54556605, 0.17411885,
       0.03053323, 0.5715797 , 0.59394428, 0.21438789, 0.2338021 ,
       0.30595668, 0.21681254, 0.94373632, 0.62069129, 0.77478568,
       0.32008104, 0.39744562, 0.09458661, 0.31254953, 0.99469

In [6]:
# 2. Pick scales -- linear data in x & y, use linear scales in x & y
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

In [7]:
bqplot.LinearScale? # so this is basically a mapping between data & 2D-plot space

In [8]:
# 3. Marks -- Line plot for now
lines = bqplot.Lines(x=x, y=y, scales = {'x':x_sc, 'y':y_sc})
# sometimes we put interactivity here

In [9]:
bqplot.Lines? # how our data will "look" on our plot

In [10]:
# 4. Axis for, in this case, x & y
ax_x = bqplot.Axis(scale=x_sc, label='X Value')
ax_y = bqplot.Axis(scale=y_sc, label='Y Value', orientation='vertical')

In [11]:
bqplot.Axis?

In [12]:
# 5. often times interactivity goes here... but not yet!

In [13]:
# Finally: put everything together into a Figure object
fig = bqplot.Figure(marks=[lines], axes=[ax_x, ax_y])

In [14]:
bqplot.Figure?

In [17]:
#display(fig)
fig

Figure(axes=[Axis(label='X Value', scale=LinearScale(), side='bottom'), Axis(label='Y Value', orientation='ver…

So we did all this weird axes/scales/figure/marks stuff, to add interactions -- let's try adding a PanZoom interaction!

In [18]:
pz = bqplot.interacts.PanZoom( scales = {'x': [x_sc], 'y': [y_sc]})

In [23]:
bqplot.interacts.PanZoom?

In [21]:
fig = bqplot.Figure(marks=[lines], axes=[ax_x, ax_y], interaction=pz)

In [22]:
fig

Figure(axes=[Axis(label='X Value', scale=LinearScale(), side='bottom'), Axis(label='Y Value', orientation='ver…

## 2. Random scatter plot

In [24]:
# 1. Data
x = np.random.random(100)

In [25]:
x

array([0.03448209, 0.10931299, 0.16087847, 0.36668644, 0.56893066,
       0.65678566, 0.78152921, 0.7458284 , 0.76321515, 0.93704451,
       0.76704335, 0.34532201, 0.0507685 , 0.37185718, 0.11473612,
       0.73531584, 0.76687874, 0.88144521, 0.26277716, 0.71176752,
       0.09810827, 0.8258311 , 0.31442952, 0.51452295, 0.32831092,
       0.86401844, 0.45051218, 0.53121204, 0.32471366, 0.35169893,
       0.82591383, 0.27608212, 0.81192884, 0.3384185 , 0.40344093,
       0.53744622, 0.27169063, 0.64835151, 0.19608727, 0.70969556,
       0.56800833, 0.16611368, 0.97125951, 0.51905726, 0.49304465,
       0.82708318, 0.24147173, 0.45624365, 0.6222716 , 0.04574119,
       0.82054072, 0.41882995, 0.51693418, 0.34139965, 0.28332709,
       0.2324163 , 0.75864439, 0.12854946, 0.49024657, 0.36124736,
       0.45761223, 0.33475659, 0.01659763, 0.91285045, 0.46340185,
       0.49756991, 0.2453416 , 0.28589968, 0.69991454, 0.37025564,
       0.11407419, 0.91692293, 0.7469402 , 0.81683611, 0.47864

In [26]:
y = np.random.random(100)

In [27]:
y

array([0.36018156, 0.64825979, 0.62858504, 0.79245382, 0.04759542,
       0.79779226, 0.31685257, 0.07998768, 0.75092387, 0.42242889,
       0.51045386, 0.68840989, 0.88516467, 0.11842245, 0.81789376,
       0.23966877, 0.97333194, 0.76708968, 0.6965742 , 0.88320432,
       0.86490792, 0.57254605, 0.7812842 , 0.98362059, 0.37231873,
       0.56322321, 0.13672946, 0.80344057, 0.0432476 , 0.04058671,
       0.3308263 , 0.14504108, 0.11713596, 0.93001856, 0.69700524,
       0.04702853, 0.05123171, 0.88770543, 0.72165254, 0.22231494,
       0.73017774, 0.99550984, 0.68328093, 0.58444651, 0.31895253,
       0.175433  , 0.04330077, 0.16418444, 0.23125295, 0.93188555,
       0.08323757, 0.31237806, 0.284286  , 0.76518229, 0.55491705,
       0.27633258, 0.65905243, 0.56936207, 0.5786479 , 0.64135523,
       0.69832045, 0.8642296 , 0.73974577, 0.01116523, 0.05170672,
       0.22849442, 0.1068327 , 0.89899437, 0.97644821, 0.32702821,
       0.40097209, 0.75580861, 0.59699624, 0.92128131, 0.39582

In [28]:
# 2. create some linear scales (again!)
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

In [29]:
# 3. Axis objects based on these scales
ax_x = bqplot.Axis(scale = x_sc, label="X")
ax_y = bqplot.Axis(scale = y_sc, label="Y", orientation='vertical')

Before we did a "Line" mark.  For a scatter plot, we'll do a "Scatter" mark!

In [30]:
# 4. Mark
scatters = bqplot.Scatter(x = x, y = y, scales={'x':x_sc, 'y':y_sc})

In [31]:
bqplot.Scatter?

In [33]:
# 5. interaction -- FastIntervalSelector
#.  I want to select an interval of points along the x-axis
bqplot.interacts.FastIntervalSelector?

In [34]:
selector = bqplot.interacts.FastIntervalSelector(scale=x_sc, marks=[scatters])

In [35]:
# finally -- a figure!
fig = bqplot.Figure(marks=[scatters], axes=[ax_x, ax_y], interaction = selector)
fig

Figure(axes=[Axis(label='X', scale=LinearScale(), side='bottom'), Axis(label='Y', orientation='vertical', scal…

In [36]:
selector.selected

array([0.51203008, 0.84865143])

We can change the look of the "scatters" marks based on selection:

In [37]:
scatters.unselected_style = {'opacity':0.8} # a little see-through when not selected
scatters.selected_style={'fill':'red', 'stroke':'yellow'}

In [38]:
fig

Figure(axes=[Axis(label='X', scale=LinearScale(), side='bottom'), Axis(label='Y', orientation='vertical', scal…

In [39]:
x

array([0.03448209, 0.10931299, 0.16087847, 0.36668644, 0.56893066,
       0.65678566, 0.78152921, 0.7458284 , 0.76321515, 0.93704451,
       0.76704335, 0.34532201, 0.0507685 , 0.37185718, 0.11473612,
       0.73531584, 0.76687874, 0.88144521, 0.26277716, 0.71176752,
       0.09810827, 0.8258311 , 0.31442952, 0.51452295, 0.32831092,
       0.86401844, 0.45051218, 0.53121204, 0.32471366, 0.35169893,
       0.82591383, 0.27608212, 0.81192884, 0.3384185 , 0.40344093,
       0.53744622, 0.27169063, 0.64835151, 0.19608727, 0.70969556,
       0.56800833, 0.16611368, 0.97125951, 0.51905726, 0.49304465,
       0.82708318, 0.24147173, 0.45624365, 0.6222716 , 0.04574119,
       0.82054072, 0.41882995, 0.51693418, 0.34139965, 0.28332709,
       0.2324163 , 0.75864439, 0.12854946, 0.49024657, 0.36124736,
       0.45761223, 0.33475659, 0.01659763, 0.91285045, 0.46340185,
       0.49756991, 0.2453416 , 0.28589968, 0.69991454, 0.37025564,
       0.11407419, 0.91692293, 0.7469402 , 0.81683611, 0.47864

In [40]:
y

array([0.36018156, 0.64825979, 0.62858504, 0.79245382, 0.04759542,
       0.79779226, 0.31685257, 0.07998768, 0.75092387, 0.42242889,
       0.51045386, 0.68840989, 0.88516467, 0.11842245, 0.81789376,
       0.23966877, 0.97333194, 0.76708968, 0.6965742 , 0.88320432,
       0.86490792, 0.57254605, 0.7812842 , 0.98362059, 0.37231873,
       0.56322321, 0.13672946, 0.80344057, 0.0432476 , 0.04058671,
       0.3308263 , 0.14504108, 0.11713596, 0.93001856, 0.69700524,
       0.04702853, 0.05123171, 0.88770543, 0.72165254, 0.22231494,
       0.73017774, 0.99550984, 0.68328093, 0.58444651, 0.31895253,
       0.175433  , 0.04330077, 0.16418444, 0.23125295, 0.93188555,
       0.08323757, 0.31237806, 0.284286  , 0.76518229, 0.55491705,
       0.27633258, 0.65905243, 0.56936207, 0.5786479 , 0.64135523,
       0.69832045, 0.8642296 , 0.73974577, 0.01116523, 0.05170672,
       0.22849442, 0.1068327 , 0.89899437, 0.97644821, 0.32702821,
       0.40097209, 0.75580861, 0.59699624, 0.92128131, 0.39582

In [41]:
y.shape

(100,)

## 3. Heatmap (2d Data) with random points

In [42]:
# 1. Data
data = np.random.random( (10, 10) )

In [74]:
data

array([[0.58989414, 0.68397708, 0.66278601, 0.5408976 , 0.9693185 ,
        0.68700492, 0.173914  , 0.64861625, 0.30780544, 0.11771333],
       [0.41375264, 0.60636106, 0.05731498, 0.67746146, 0.14992504,
        0.04442673, 0.90670582, 0.51955875, 0.96080304, 0.5515289 ],
       [0.48097145, 0.37344345, 0.17353181, 0.4578347 , 0.19953201,
        0.03414197, 0.01511233, 0.37247233, 0.59231042, 0.31648153],
       [0.38612009, 0.22631793, 0.96126498, 0.89103813, 0.30569113,
        0.1460685 , 0.75010262, 0.76501239, 0.04677228, 0.34132688],
       [0.37063089, 0.5650219 , 0.60433404, 0.68985143, 0.64837045,
        0.94918305, 0.73891296, 0.49631326, 0.93788438, 0.30722456],
       [0.64345905, 0.23958286, 0.0480288 , 0.90451934, 0.99126259,
        0.84703278, 0.12930839, 0.83114047, 0.74514455, 0.73679432],
       [0.60245444, 0.55327658, 0.9622388 , 0.609966  , 0.09229455,
        0.79087311, 0.30824441, 0.79772483, 0.12119156, 0.89343157],
       [0.57306867, 0.31830395, 0.9012809

In [75]:
data.shape

(10, 10)

In [76]:
data[0, 5]

0.6870049178157462

In [45]:
# 2. Scale - color scale
col_sc = bqplot.ColorScale()

In [46]:
bqplot.ColorScale?

In [47]:
# 3. Axis -- NOT plot axis

In [56]:
bqplot.GridHeatMap?

In [49]:
# 4. Mark -- heatmap
heat_map = bqplot.GridHeatMap(color = data, scales = {'color':col_sc})

In [50]:
# 5. Interactions -- skpping as well!

In [51]:
# Finally, a figure!
fig = bqplot.Figure(marks = [heat_map])
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.58989…

First, changing the color scheme of our heatmap:

In [52]:
# 1. Data -- same

# 2. Scale - color scale
col_sc = bqplot.ColorScale(scheme="Reds") # this is the update!

# 3. Axis -- NOT plot axis

# 4. Mark -- heatmap
heat_map = bqplot.GridHeatMap(color = data, scales = {'color':col_sc})

# 5. Interactions -- skipping as well!

# Finally, a figure!
fig = bqplot.Figure(marks = [heat_map])
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.58989…

Add in some color axis so that we know how our data maps to our colors:

In [54]:
# 1. Data -- same

# 2. Scale - color scale
col_sc = bqplot.ColorScale(scheme="Reds") 

# 3. Axis -- for colors, the axis is a colorbar!
ax_col = bqplot.ColorAxis(scale = col_sc, orientation='vertical', side='right') # this is the update!

# 4. Mark -- heatmap
heat_map = bqplot.GridHeatMap(color = data, scales = {'color':col_sc})

# 5. Interactions -- skipping as well!

# Finally, a figure!
fig = bqplot.Figure(marks = [heat_map], axes=[ax_col]) # have to add this axis to my figure object!
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right')], fig_margin={'t…

Keep adding -- add some x & y axis labels.  For now -- just use the defaults.

In [57]:
# 1. Data -- same

# 2. Scale - color scale
col_sc = bqplot.ColorScale(scheme="Reds") 
# this is because the "bins" are just bins -- their order is NOT numerically important
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- for colors, the axis is a colorbar!
ax_col = bqplot.ColorAxis(scale = col_sc, orientation='vertical', side='right') 
ax_x = bqplot.Axis(scale = x_sc) # same x/y ax we had before
ax_y = bqplot.Axis(scale = y_sc, orientation='vertical')

# 4. Mark -- heatmap
heat_map = bqplot.GridHeatMap(color = data, scales = {'color':col_sc, 'row':y_sc, 'column':x_sc})

# 5. Interactions -- skipping as well!

# Finally, a figure!
fig = bqplot.Figure(marks = [heat_map], axes=[ax_col, ax_x, ax_y]) # have to add this axis to my figure object!
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(scale=Ordi…

In [58]:
bqplot.GridHeatMap?

By looking through some doc strings we might get the sense that we have some interactions, selection, change the selected style... look through some examples as well.

In [59]:
# 1. Data -- same

# 2. Scale - color scale
col_sc = bqplot.ColorScale(scheme="Reds") 
# this is because the "bins" are just bins -- their order is NOT numerically important
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- for colors, the axis is a colorbar!
ax_col = bqplot.ColorAxis(scale = col_sc, orientation='vertical', side='right') 
ax_x = bqplot.Axis(scale = x_sc) # same x/y ax we had before
ax_y = bqplot.Axis(scale = y_sc, orientation='vertical')

# 4. Mark -- heatmap
heat_map = bqplot.GridHeatMap(color = data, scales = {'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             anchor_style={'fill':'blue'},
                             selected_style={'opacity':1.0},
                             unselected_style={'opacity':0.8})

# 5. Interactions -- going to be built into the GridHeatMap mark

# Finally, a figure!
fig = bqplot.Figure(marks = [heat_map], axes=[ax_col, ax_x, ax_y]) # have to add this axis to my figure object!
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(scale=Ordi…

In [60]:
heat_map.selected

array([[5, 4]])

I'm going to start building a dashboard: label that shows the value of the data in a selected grid & grid heatmap itself

In [61]:
mySelectedLabel = ipywidgets.Label()

In [62]:
# first, just print out what is changing
def on_selected(change):
    print(change)

In [63]:
# 1. Data -- same

# 2. Scale - color scale
col_sc = bqplot.ColorScale(scheme="Reds") 
# this is because the "bins" are just bins -- their order is NOT numerically important
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- for colors, the axis is a colorbar!
ax_col = bqplot.ColorAxis(scale = col_sc, orientation='vertical', side='right') 
ax_x = bqplot.Axis(scale = x_sc) # same x/y ax we had before
ax_y = bqplot.Axis(scale = y_sc, orientation='vertical')

# 4. Mark -- heatmap
heat_map = bqplot.GridHeatMap(color = data, scales = {'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             anchor_style={'fill':'blue'},
                             selected_style={'opacity':1.0},
                             unselected_style={'opacity':0.8})

# 5. Interactions -- going to be built into the GridHeatMap mark (how things *look* when selection happens)
# BUT I'm going to define what happens when the interaction takes place (something is selected)
heat_map.observe(on_selected, 'selected')

# Finally, a figure!
fig = bqplot.Figure(marks = [heat_map], axes=[ax_col, ax_x, ax_y]) # have to add this axis to my figure object!
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(scale=Ordi…

{'name': 'selected', 'old': None, 'new': array([[5, 3]]), 'owner': GridHeatMap(anchor_style={'fill': 'blue'}, color=array([[0.58989414, 0.68397708, 0.66278601, 0.5408976 , 0.9693185 ,
        0.68700492, 0.173914  , 0.64861625, 0.30780544, 0.11771333],
       [0.41375264, 0.60636106, 0.05731498, 0.67746146, 0.14992504,
        0.04442673, 0.90670582, 0.51955875, 0.96080304, 0.5515289 ],
       [0.48097145, 0.37344345, 0.17353181, 0.4578347 , 0.19953201,
        0.03414197, 0.01511233, 0.37247233, 0.59231042, 0.31648153],
       [0.38612009, 0.22631793, 0.96126498, 0.89103813, 0.30569113,
        0.1460685 , 0.75010262, 0.76501239, 0.04677228, 0.34132688],
       [0.37063089, 0.5650219 , 0.60433404, 0.68985143, 0.64837045,
        0.94918305, 0.73891296, 0.49631326, 0.93788438, 0.30722456],
       [0.64345905, 0.23958286, 0.0480288 , 0.90451934, 0.99126259,
        0.84703278, 0.12930839, 0.83114047, 0.74514455, 0.73679432],
       [0.60245444, 0.55327658, 0.9622388 , 0.609966  , 0.0922

In [65]:
# first, just print out what is changing, what is selected
def on_selected(change):
    print(change['owner'].selected)
    
# 1. Data -- same

# 2. Scale - color scale
col_sc = bqplot.ColorScale(scheme="Reds") 
# this is because the "bins" are just bins -- their order is NOT numerically important
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- for colors, the axis is a colorbar!
ax_col = bqplot.ColorAxis(scale = col_sc, orientation='vertical', side='right') 
ax_x = bqplot.Axis(scale = x_sc) # same x/y ax we had before
ax_y = bqplot.Axis(scale = y_sc, orientation='vertical')

# 4. Mark -- heatmap
heat_map = bqplot.GridHeatMap(color = data, scales = {'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             anchor_style={'fill':'blue'},
                             selected_style={'opacity':1.0},
                             unselected_style={'opacity':0.8})

# 5. Interactions -- going to be built into the GridHeatMap mark (how things *look* when selection happens)
# BUT I'm going to define what happens when the interaction takes place (something is selected)
heat_map.observe(on_selected, 'selected')

# Finally, a figure!
fig = bqplot.Figure(marks = [heat_map], axes=[ax_col, ax_x, ax_y]) # have to add this axis to my figure object!
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(scale=Ordi…

[[0 0]]
[[3 4]]
[[5 6]]
[[5 7]
 [5 6]]
[[4 7]
 [4 6]
 [5 6]
 [5 7]]
[[3 6]
 [4 6]
 [5 6]]
[[2 7]
 [2 6]
 [3 6]
 [3 7]
 [4 6]
 [4 7]
 [5 6]
 [5 7]]
[[6 8]
 [5 6]
 [5 7]
 [5 8]
 [6 6]
 [6 7]]
[[4 8]
 [4 6]
 [4 7]
 [5 6]
 [5 7]
 [5 8]]
[[3 6]]


In [66]:
# first, just print out what is changing, what is selected
# only support 1 selected grid
def on_selected(change):
    if len(change['owner'].selected) == 1:
        print(change['owner'].selected[0])
    
# 1. Data -- same

# 2. Scale - color scale
col_sc = bqplot.ColorScale(scheme="Reds") 
# this is because the "bins" are just bins -- their order is NOT numerically important
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- for colors, the axis is a colorbar!
ax_col = bqplot.ColorAxis(scale = col_sc, orientation='vertical', side='right') 
ax_x = bqplot.Axis(scale = x_sc) # same x/y ax we had before
ax_y = bqplot.Axis(scale = y_sc, orientation='vertical')

# 4. Mark -- heatmap
heat_map = bqplot.GridHeatMap(color = data, scales = {'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             anchor_style={'fill':'blue'},
                             selected_style={'opacity':1.0},
                             unselected_style={'opacity':0.8})

# 5. Interactions -- going to be built into the GridHeatMap mark (how things *look* when selection happens)
# BUT I'm going to define what happens when the interaction takes place (something is selected)
heat_map.observe(on_selected, 'selected')

# Finally, a figure!
fig = bqplot.Figure(marks = [heat_map], axes=[ax_col, ax_x, ax_y]) # have to add this axis to my figure object!
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(scale=Ordi…

[7 3]
[2 4]
[2 2]
[3 2]
[3 3]
[4 2]
[6 2]


In [67]:
# first, just print out what is changing, what is selected
# only support 1 selected grid
def on_selected(change):
    if len(change['owner'].selected) == 1:
        #print(change['owner'].selected[0])
        i, j = change['owner'].selected[0]
        v = data[i,j] # grabbing the underlying datavalue associated with this row/column
        mySelectedLabel.value = 'Data Value = ' + str(v)
    
# 1. Data -- same

# 2. Scale - color scale
col_sc = bqplot.ColorScale(scheme="Reds") 
# this is because the "bins" are just bins -- their order is NOT numerically important
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- for colors, the axis is a colorbar!
ax_col = bqplot.ColorAxis(scale = col_sc, orientation='vertical', side='right') 
ax_x = bqplot.Axis(scale = x_sc) # same x/y ax we had before
ax_y = bqplot.Axis(scale = y_sc, orientation='vertical')

# 4. Mark -- heatmap
heat_map = bqplot.GridHeatMap(color = data, scales = {'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             anchor_style={'fill':'blue'},
                             selected_style={'opacity':1.0},
                             unselected_style={'opacity':0.8})

# 5. Interactions -- going to be built into the GridHeatMap mark (how things *look* when selection happens)
# BUT I'm going to define what happens when the interaction takes place (something is selected)
heat_map.observe(on_selected, 'selected')

# Finally, a figure!
fig = bqplot.Figure(marks = [heat_map], axes=[ax_col, ax_x, ax_y]) # have to add this axis to my figure object!
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(scale=Ordi…

In [69]:
mySelectedLabel

Label(value='Data Value = 0.7653099463059154')

Show both the widget & the heatmap at the same time:

In [70]:
# first, just print out what is changing, what is selected
# only support 1 selected grid
def on_selected(change):
    if len(change['owner'].selected) == 1:
        #print(change['owner'].selected[0])
        i, j = change['owner'].selected[0]
        v = data[i,j] # grabbing the underlying datavalue associated with this row/column
        mySelectedLabel.value = 'Data Value = ' + str(v)
    
# 1. Data -- same

# 2. Scale - color scale
col_sc = bqplot.ColorScale(scheme="Reds") 
# this is because the "bins" are just bins -- their order is NOT numerically important
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# 3. Axis -- for colors, the axis is a colorbar!
ax_col = bqplot.ColorAxis(scale = col_sc, orientation='vertical', side='right') 
ax_x = bqplot.Axis(scale = x_sc) # same x/y ax we had before
ax_y = bqplot.Axis(scale = y_sc, orientation='vertical')

# 4. Mark -- heatmap
heat_map = bqplot.GridHeatMap(color = data, scales = {'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             anchor_style={'fill':'blue'},
                             selected_style={'opacity':1.0},
                             unselected_style={'opacity':0.8})

# 5. Interactions -- going to be built into the GridHeatMap mark (how things *look* when selection happens)
# BUT I'm going to define what happens when the interaction takes place (something is selected)
heat_map.observe(on_selected, 'selected')

# Finally, a figure!
fig = bqplot.Figure(marks = [heat_map], axes=[ax_col, ax_x, ax_y]) # have to add this axis to my figure object!
#fig

# combine the widget & figure and display both at the same time!
myDashboard = ipywidgets.VBox([mySelectedLabel, fig])
myDashboard # show the dashboard

## Multi-dimention data dashboards

In [71]:
data3d = np.random.random( (10,10, 20))

In [73]:
data3d.shape

(10, 10, 20)