# In Class Notebook, Week 06

You can always access the URL of this notebook: https://github.com/UIUC-iSchool-DataViz/is445_bcubcg_fall2022/blob/master/week06/inClass_week06.ipynb 

Or post the URL into the nbviewer interface for a plain-text rendering:

https://kokes.github.io/nbviewer.js/viewer.html

In [1]:
import pandas as pd
import numpy as np
import ipywidgets
import matplotlib.pyplot as plt
import bqplot

## Quick review from recording last week

In [2]:
# Step 1: data
data = np.random.random((10,10))

In [4]:
data.shape

(10, 10)

In [5]:
bqplot.GridHeatMap?

In [6]:
bqplot.ColorScale?

In [7]:
# Step 2: define scales
col_sc = bqplot.ColorScale()

# Step 3: define our axis -- ignore right now

# Step 4: defien marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

# Step 5: interactions -- also ignore for now

# finally, a figure
fig = bqplot.Figure(marks=[heat_map])
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.27531…

In [8]:
# Step 2: define scales
col_sc = bqplot.ColorScale(scheme='Greens')

# Step 3: define our axis -- ignore right now

# Step 4: define marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

# Step 5: interactions -- also ignore for now

# finally, a figure
fig = bqplot.Figure(marks=[heat_map])
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.27531…

In [9]:
bqplot.ColorAxis?

In [10]:
# Step 2: define scales
col_sc = bqplot.ColorScale(scheme='Greens')

# Step 3: define our axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')

# Step 4: define marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

# Step 5: interactions -- also ignore for now

# finally, a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right')], fig_margin={…

In [11]:
bqplot.OrdinalScale?

In [13]:
# Step 2: define scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# Step 3: define our axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# Step 4: define marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc})

# Step 5: interactions -- also ignore for now

# finally, a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax,x_ax,y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right'), Axis(scale=Or…

In [15]:
# Step 2: define scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# Step 3: define our axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# Step 4: define marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'magenta'})

# Step 5: interactions

# finally, a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax,x_ax,y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right'), Axis(scale=Or…

In [16]:
heat_map.keys

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'anchor_style',
 'apply_clip',
 'color',
 'column',
 'column_align',
 'display_format',
 'display_legend',
 'enable_hover',
 'font_style',
 'interactions',
 'labels',
 'null_color',
 'opacity',
 'preserve_domain',
 'row',
 'row_align',
 'scales',
 'scales_metadata',
 'selected',
 'selected_style',
 'stroke',
 'tooltip',
 'tooltip_location',
 'tooltip_style',
 'unselected_style',
 'visible']

In [18]:
heat_map.selected

array([[2, 1]])

In [19]:
def on_selected(change):
    print(change)

In [20]:
# Step 2: define scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# Step 3: define our axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# Step 4: define marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'magenta'})

# Step 5: interactions
heat_map.observe(on_selected, 'selected')

# finally, a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax,x_ax,y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right'), Axis(scale=Or…

{'name': 'selected', 'old': None, 'new': array([[2, 2]]), 'owner': GridHeatMap(color=array([[0.27531265, 0.97925689, 0.17876959, 0.31435629, 0.34298199,
        0.18930713, 0.3980785 , 0.49119594, 0.15111856, 0.95393713],
       [0.25814584, 0.87138735, 0.6611456 , 0.93854362, 0.70081037,
        0.94525011, 0.81874894, 0.7552403 , 0.30715503, 0.47762942],
       [0.75309501, 0.07768045, 0.98737034, 0.68765784, 0.25105678,
        0.3508429 , 0.4730336 , 0.97845577, 0.914496  , 0.15110906],
       [0.71736885, 0.22335415, 0.98448271, 0.05456288, 0.24748977,
        0.86375856, 0.11782623, 0.09663626, 0.89093422, 0.69493642],
       [0.71915883, 0.34589913, 0.26843566, 0.65643454, 0.17711863,
        0.54239279, 0.22771757, 0.62434974, 0.16783129, 0.44128787],
       [0.7175395 , 0.58292037, 0.81196601, 0.17438552, 0.72422618,
        0.62577996, 0.54679991, 0.24499123, 0.05786865, 0.19521742],
       [0.67068352, 0.66363339, 0.40389108, 0.69840189, 0.80240875,
        0.85606823, 0.787

In [21]:
def on_selected(change):
    print(change['owner'].selected)
    
# Step 2: define scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# Step 3: define our axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# Step 4: define marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'magenta'})

# Step 5: interactions
heat_map.observe(on_selected, 'selected')

# finally, a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax,x_ax,y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right'), Axis(scale=Or…

[[2 1]]
[[1 2]]
[[0 3]]
[[2 3]]
[[2 4]
 [2 3]]
[[1 4]
 [1 3]
 [2 3]
 [2 4]]
[[0 4]
 [0 3]
 [1 3]
 [1 4]
 [2 3]
 [2 4]]
[[3 4]]
[[0 5]]


In [22]:
def on_selected(change):
    if len(change['owner'].selected) == 1: # no regions, only single bins selected
        print(change['owner'].selected[0])
    
# Step 2: define scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# Step 3: define our axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# Step 4: define marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'magenta'})

# Step 5: interactions
heat_map.observe(on_selected, 'selected')

# finally, a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax,x_ax,y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right'), Axis(scale=Or…

[2 1]
[1 2]
[3 2]
[5 3]
[6 3]
[7 7]
[3 3]
[7 8]
[6 9]
[5 4]


In [23]:
selectedLabel = ipywidgets.Label()

In [24]:
selectedLabel

Label(value='')

In [31]:
heat_map.selected[0]

array([6, 9])

In [32]:
i,j = heat_map.selected[0]
data[i,j]

0.9951277514402208

In [34]:
selectedLabel.value = 'Data value=' + str(data[i,j])
selectedLabel

Label(value='Data value=0.9951277514402208')

In [36]:
def on_selected(change):
    if len(change['owner'].selected) == 1: # no regions, only single bins selected
        #print(change['owner'].selected[0])
        i,j = change['owner'].selected[0]
        v = data[i,j]
        selectedLabel.value = 'Data Value = ' + str(v)
    
# Step 2: define scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# Step 3: define our axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# Step 4: define marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'magenta'})

# Step 5: interactions
heat_map.observe(on_selected, 'selected')

# finally, a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax,x_ax,y_ax])
#fig
myDashboard = ipywidgets.VBox([selectedLabel,fig])
myDashboard

## 3D Data (random)

In [37]:
data3d = np.random.random((10,10,20))

In [38]:
data3d.shape

(10, 10, 20)

In [39]:
data3d[0,0,:]

array([0.32588475, 0.43938101, 0.07153513, 0.99609673, 0.82356502,
       0.0535677 , 0.42681183, 0.94361028, 0.89697943, 0.93719966,
       0.4528262 , 0.19206377, 0.15592736, 0.96650288, 0.71467114,
       0.44150996, 0.34095281, 0.59526475, 0.43049586, 0.83280355])

In [40]:
data3d[0,0,:].mean()

0.5518824911833982

In [42]:
data3d.mean(axis=2).shape

(10, 10)

In [43]:
selectedLabel3d = ipywidgets.Label()

In [45]:
def on_selected(change):
    if len(change['owner'].selected) == 1: # no regions, only single bins selected
        i,j = change['owner'].selected[0]
        v = data3d[i,j,:].mean()
        selectedLabel3d.value = 'Data Mean = ' + str(v)
    
# Step 2: define scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# Step 3: define our axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# Step 4: define marks
heat_map = bqplot.GridHeatMap(color=data3d.mean(axis=2), scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'magenta'})

# Step 5: interactions
heat_map.observe(on_selected, 'selected')

# finally, a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax,x_ax,y_ax])
#fig
myDashboard = ipywidgets.VBox([selectedLabel3d,fig])
myDashboard

In [46]:
#1. Data for histogram (starting with a hard-coded value)
i,j = 0,0
data3d[i,j]

array([0.32588475, 0.43938101, 0.07153513, 0.99609673, 0.82356502,
       0.0535677 , 0.42681183, 0.94361028, 0.89697943, 0.93719966,
       0.4528262 , 0.19206377, 0.15592736, 0.96650288, 0.71467114,
       0.44150996, 0.34095281, 0.59526475, 0.43049586, 0.83280355])

In [47]:
# 2. Scales for histogram
x_sch = bqplot.LinearScale() # numerical data
y_sch = bqplot.LinearScale() # numerical data for the distribution

In [48]:
# 3. Axis for histogram
x_axh = bqplot.Axis(scale=x_sch, label='Value of 3rd Axis')
y_axh = bqplot.Axis(scale=y_sch, orientation='vertical', label='Frequency')

In [49]:
bqplot.Hist?

In [50]:
# 4. Marks for histogram
hist = bqplot.Hist(sample=data3d[i,j,:], # hard-coded for now
                  normalized=False, # to get counts instead of density
                  scales={'sample':x_sch, 'count':y_sch}, 
                  bins=5)

In [51]:
# 5. interactions -- none right now for the histogram plot

In [52]:
# finally, a figure
figh = bqplot.Figure(marks=[hist],axes=[x_axh, y_axh])
figh

Figure(axes=[Axis(label='Value of 3rd Axis', scale=LinearScale(), side='bottom'), Axis(label='Frequency', orie…

In [53]:
hist.keys

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'apply_clip',
 'bins',
 'colors',
 'count',
 'display_legend',
 'enable_hover',
 'interactions',
 'labels',
 'midpoints',
 'normalized',
 'opacities',
 'preserve_domain',
 'sample',
 'scales',
 'scales_metadata',
 'selected',
 'selected_style',
 'stroke',
 'tooltip',
 'tooltip_location',
 'tooltip_style',
 'unselected_style',
 'visible']

In [54]:
hist.sample

array([0.32588475, 0.43938101, 0.07153513, 0.99609673, 0.82356502,
       0.0535677 , 0.42681183, 0.94361028, 0.89697943, 0.93719966,
       0.4528262 , 0.19206377, 0.15592736, 0.96650288, 0.71467114,
       0.44150996, 0.34095281, 0.59526475, 0.43049586, 0.83280355])

In [58]:
def on_selected(change):
    if len(change['owner'].selected) == 1: # no regions, only single bins selected
        i,j = change['owner'].selected[0]
        v = data3d[i,j,:].mean()
        selectedLabel3d.value = 'Data Mean = ' + str(v) # updating the trait of the label
        hist.sample = data3d[i,j,:] # updating the trait "sample" of histogram
    
# Step 2: define scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# Step 3: define our axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# Step 4: define marks
heat_map = bqplot.GridHeatMap(color=data3d.mean(axis=2), scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'magenta'})

# Step 5: interactions
heat_map.observe(on_selected, 'selected')

# finally, a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax,x_ax,y_ax])
#fig
#myDashboard = ipywidgets.VBox([selectedLabel3d,fig])
fig.layout.min_width='500px'
figh.layout.min_width='500px'
figures = ipywidgets.HBox([fig, figh]) # fig=heat map (driver), figh=histgram (updates)
myDashboard = ipywidgets.VBox([selectedLabel3d, figures])
myDashboard

In [61]:
hist.bins = 10

In [62]:
bins_slider = ipywidgets.IntSlider(value=5,min=1, max=data3d.shape[2])
bins_slider

IntSlider(value=5, max=20, min=1)

In [63]:
ipywidgets.jslink((bins_slider,'value'),(hist,'bins'))

Link(source=(IntSlider(value=2, max=20, min=1), 'value'), target=(Hist(colors=['steelblue'], count=array([2., …

In [64]:
figures = ipywidgets.HBox([fig,figh])
controls = ipywidgets.HBox([selectedLabel3d, bins_slider])
myDashboard = ipywidgets.VBox([controls, figures])
myDashboard