# In Class Notebook, Week 06

You can always access the URL of this notebook: https://github.com/UIUC-iSchool-DataViz/is445_bcubcg_fall2022/blob/master/week06/inClass_week06.ipynb 

Or post the URL into the nbviewer interface for a plain-text rendering:

https://kokes.github.io/nbviewer.js/viewer.html

In [1]:
import pandas as pd
import numpy as np
import ipywidgets
import matplotlib.pyplot as plt
import bqplot

## Quick review from recording last week

In [2]:
# Step 1: data
data = np.random.random((10,10))

In [4]:
data.shape

(10, 10)

In [5]:
bqplot.GridHeatMap?

In [6]:
bqplot.ColorScale?

In [7]:
# Step 2: define scales
col_sc = bqplot.ColorScale()

# Step 3: define our axis -- ignore right now

# Step 4: defien marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

# Step 5: interactions -- also ignore for now

# finally, a figure
fig = bqplot.Figure(marks=[heat_map])
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.27531…

In [8]:
# Step 2: define scales
col_sc = bqplot.ColorScale(scheme='Greens')

# Step 3: define our axis -- ignore right now

# Step 4: define marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

# Step 5: interactions -- also ignore for now

# finally, a figure
fig = bqplot.Figure(marks=[heat_map])
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.27531…

In [9]:
bqplot.ColorAxis?

In [10]:
# Step 2: define scales
col_sc = bqplot.ColorScale(scheme='Greens')

# Step 3: define our axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')

# Step 4: define marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

# Step 5: interactions -- also ignore for now

# finally, a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right')], fig_margin={…

In [11]:
bqplot.OrdinalScale?

In [13]:
# Step 2: define scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# Step 3: define our axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# Step 4: define marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc})

# Step 5: interactions -- also ignore for now

# finally, a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax,x_ax,y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right'), Axis(scale=Or…

In [15]:
# Step 2: define scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# Step 3: define our axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# Step 4: define marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'magenta'})

# Step 5: interactions

# finally, a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax,x_ax,y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right'), Axis(scale=Or…

In [16]:
heat_map.keys

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'anchor_style',
 'apply_clip',
 'color',
 'column',
 'column_align',
 'display_format',
 'display_legend',
 'enable_hover',
 'font_style',
 'interactions',
 'labels',
 'null_color',
 'opacity',
 'preserve_domain',
 'row',
 'row_align',
 'scales',
 'scales_metadata',
 'selected',
 'selected_style',
 'stroke',
 'tooltip',
 'tooltip_location',
 'tooltip_style',
 'unselected_style',
 'visible']

In [18]:
heat_map.selected

array([[2, 1]])

In [19]:
def on_selected(change):
    print(change)

In [20]:
# Step 2: define scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# Step 3: define our axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# Step 4: define marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'magenta'})

# Step 5: interactions
heat_map.observe(on_selected, 'selected')

# finally, a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax,x_ax,y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right'), Axis(scale=Or…

{'name': 'selected', 'old': None, 'new': array([[2, 2]]), 'owner': GridHeatMap(color=array([[0.27531265, 0.97925689, 0.17876959, 0.31435629, 0.34298199,
        0.18930713, 0.3980785 , 0.49119594, 0.15111856, 0.95393713],
       [0.25814584, 0.87138735, 0.6611456 , 0.93854362, 0.70081037,
        0.94525011, 0.81874894, 0.7552403 , 0.30715503, 0.47762942],
       [0.75309501, 0.07768045, 0.98737034, 0.68765784, 0.25105678,
        0.3508429 , 0.4730336 , 0.97845577, 0.914496  , 0.15110906],
       [0.71736885, 0.22335415, 0.98448271, 0.05456288, 0.24748977,
        0.86375856, 0.11782623, 0.09663626, 0.89093422, 0.69493642],
       [0.71915883, 0.34589913, 0.26843566, 0.65643454, 0.17711863,
        0.54239279, 0.22771757, 0.62434974, 0.16783129, 0.44128787],
       [0.7175395 , 0.58292037, 0.81196601, 0.17438552, 0.72422618,
        0.62577996, 0.54679991, 0.24499123, 0.05786865, 0.19521742],
       [0.67068352, 0.66363339, 0.40389108, 0.69840189, 0.80240875,
        0.85606823, 0.787

In [21]:
def on_selected(change):
    print(change['owner'].selected)
    
# Step 2: define scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# Step 3: define our axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# Step 4: define marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'magenta'})

# Step 5: interactions
heat_map.observe(on_selected, 'selected')

# finally, a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax,x_ax,y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right'), Axis(scale=Or…

[[2 1]]
[[1 2]]
[[0 3]]
[[2 3]]
[[2 4]
 [2 3]]
[[1 4]
 [1 3]
 [2 3]
 [2 4]]
[[0 4]
 [0 3]
 [1 3]
 [1 4]
 [2 3]
 [2 4]]
[[3 4]]
[[0 5]]


In [22]:
def on_selected(change):
    if len(change['owner'].selected) == 1: # no regions, only single bins selected
        print(change['owner'].selected[0])
    
# Step 2: define scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# Step 3: define our axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# Step 4: define marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'magenta'})

# Step 5: interactions
heat_map.observe(on_selected, 'selected')

# finally, a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax,x_ax,y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Greens'), side='right'), Axis(scale=Or…

[2 1]
[1 2]
[3 2]
[5 3]
[6 3]
[7 7]
[3 3]
[7 8]
[6 9]
[5 4]


In [23]:
selectedLabel = ipywidgets.Label()

In [24]:
selectedLabel

Label(value='')

In [31]:
heat_map.selected[0]

array([6, 9])

In [32]:
i,j = heat_map.selected[0]
data[i,j]

0.9951277514402208

In [34]:
selectedLabel.value = 'Data value=' + str(data[i,j])
selectedLabel

Label(value='Data value=0.9951277514402208')

In [36]:
def on_selected(change):
    if len(change['owner'].selected) == 1: # no regions, only single bins selected
        #print(change['owner'].selected[0])
        i,j = change['owner'].selected[0]
        v = data[i,j]
        selectedLabel.value = 'Data Value = ' + str(v)
    
# Step 2: define scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# Step 3: define our axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# Step 4: define marks
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'magenta'})

# Step 5: interactions
heat_map.observe(on_selected, 'selected')

# finally, a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax,x_ax,y_ax])
#fig
myDashboard = ipywidgets.VBox([selectedLabel,fig])
myDashboard

## 3D Data (random)

In [37]:
data3d = np.random.random((10,10,20))

In [38]:
data3d.shape

(10, 10, 20)

In [39]:
data3d[0,0,:]

array([0.32588475, 0.43938101, 0.07153513, 0.99609673, 0.82356502,
       0.0535677 , 0.42681183, 0.94361028, 0.89697943, 0.93719966,
       0.4528262 , 0.19206377, 0.15592736, 0.96650288, 0.71467114,
       0.44150996, 0.34095281, 0.59526475, 0.43049586, 0.83280355])

In [40]:
data3d[0,0,:].mean()

0.5518824911833982

In [42]:
data3d.mean(axis=2).shape

(10, 10)

In [43]:
selectedLabel3d = ipywidgets.Label()

In [45]:
def on_selected(change):
    if len(change['owner'].selected) == 1: # no regions, only single bins selected
        i,j = change['owner'].selected[0]
        v = data3d[i,j,:].mean()
        selectedLabel3d.value = 'Data Mean = ' + str(v)
    
# Step 2: define scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# Step 3: define our axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# Step 4: define marks
heat_map = bqplot.GridHeatMap(color=data3d.mean(axis=2), scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'magenta'})

# Step 5: interactions
heat_map.observe(on_selected, 'selected')

# finally, a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax,x_ax,y_ax])
#fig
myDashboard = ipywidgets.VBox([selectedLabel3d,fig])
myDashboard

In [46]:
#1. Data for histogram (starting with a hard-coded value)
i,j = 0,0
data3d[i,j]

array([0.32588475, 0.43938101, 0.07153513, 0.99609673, 0.82356502,
       0.0535677 , 0.42681183, 0.94361028, 0.89697943, 0.93719966,
       0.4528262 , 0.19206377, 0.15592736, 0.96650288, 0.71467114,
       0.44150996, 0.34095281, 0.59526475, 0.43049586, 0.83280355])

In [47]:
# 2. Scales for histogram
x_sch = bqplot.LinearScale() # numerical data
y_sch = bqplot.LinearScale() # numerical data for the distribution

In [48]:
# 3. Axis for histogram
x_axh = bqplot.Axis(scale=x_sch, label='Value of 3rd Axis')
y_axh = bqplot.Axis(scale=y_sch, orientation='vertical', label='Frequency')

In [49]:
bqplot.Hist?

In [50]:
# 4. Marks for histogram
hist = bqplot.Hist(sample=data3d[i,j,:], # hard-coded for now
                  normalized=False, # to get counts instead of density
                  scales={'sample':x_sch, 'count':y_sch}, 
                  bins=5)

In [51]:
# 5. interactions -- none right now for the histogram plot

In [52]:
# finally, a figure
figh = bqplot.Figure(marks=[hist],axes=[x_axh, y_axh])
figh

Figure(axes=[Axis(label='Value of 3rd Axis', scale=LinearScale(), side='bottom'), Axis(label='Frequency', orie…

In [53]:
hist.keys

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'apply_clip',
 'bins',
 'colors',
 'count',
 'display_legend',
 'enable_hover',
 'interactions',
 'labels',
 'midpoints',
 'normalized',
 'opacities',
 'preserve_domain',
 'sample',
 'scales',
 'scales_metadata',
 'selected',
 'selected_style',
 'stroke',
 'tooltip',
 'tooltip_location',
 'tooltip_style',
 'unselected_style',
 'visible']

In [54]:
hist.sample

array([0.32588475, 0.43938101, 0.07153513, 0.99609673, 0.82356502,
       0.0535677 , 0.42681183, 0.94361028, 0.89697943, 0.93719966,
       0.4528262 , 0.19206377, 0.15592736, 0.96650288, 0.71467114,
       0.44150996, 0.34095281, 0.59526475, 0.43049586, 0.83280355])

In [58]:
def on_selected(change):
    if len(change['owner'].selected) == 1: # no regions, only single bins selected
        i,j = change['owner'].selected[0]
        v = data3d[i,j,:].mean()
        selectedLabel3d.value = 'Data Mean = ' + str(v) # updating the trait of the label
        hist.sample = data3d[i,j,:] # updating the trait "sample" of histogram
    
# Step 2: define scales
col_sc = bqplot.ColorScale(scheme='Greens')
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# Step 3: define our axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# Step 4: define marks
heat_map = bqplot.GridHeatMap(color=data3d.mean(axis=2), scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'magenta'})

# Step 5: interactions
heat_map.observe(on_selected, 'selected')

# finally, a figure
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax,x_ax,y_ax])
#fig
#myDashboard = ipywidgets.VBox([selectedLabel3d,fig])
fig.layout.min_width='500px'
figh.layout.min_width='500px'
figures = ipywidgets.HBox([fig, figh]) # fig=heat map (driver), figh=histgram (updates)
myDashboard = ipywidgets.VBox([selectedLabel3d, figures])
myDashboard

In [61]:
hist.bins = 10

In [62]:
bins_slider = ipywidgets.IntSlider(value=5,min=1, max=data3d.shape[2])
bins_slider

IntSlider(value=5, max=20, min=1)

In [63]:
ipywidgets.jslink((bins_slider,'value'),(hist,'bins'))

Link(source=(IntSlider(value=2, max=20, min=1), 'value'), target=(Hist(colors=['steelblue'], count=array([2., …

In [64]:
figures = ipywidgets.HBox([fig,figh])
controls = ipywidgets.HBox([selectedLabel3d, bins_slider])
myDashboard = ipywidgets.VBox([controls, figures])
myDashboard

## Dashboarding with the UFO dataset

In [65]:
data_url = 'https://raw.githubusercontent.com/UIUC-iSchool-DataViz/is445_bcubcg_fall2022/main/data/ufo-scrubbed-geocoded-time-standardized-00.csv'

In [66]:
ufos = pd.read_csv(data_url, names = ["date", "city", "state", "country",
                          "shape", "duration_seconds", "duration",
                          "comment", "report_date", 
                           "latitude", "longitude"],
                  parse_dates = ["date", "report_date"])

In [67]:
len(ufos)

80332

In [69]:
nsamples = 1000
downSampleMask = np.random.choice(range(len(ufos)-1), nsamples, replace=False)
downSampleMask

array([59616, 23715, 50133, 18359, 59487, 19242, 60849, 53798, 48884,
       53898, 61309, 42465, 73393, 64915, 36512, 18316, 63753, 73525,
       13222, 15825, 77774, 60450, 19423, 45802, 63694, 76213,   858,
       11021, 71771, 33884, 56346, 45590, 22249, 49188, 69122, 24804,
       64120, 65849, 54623, 79554, 42324, 41685,  8493, 29722, 77116,
       40486,  1482,  9133, 76883, 46968, 50849, 40334, 33052, 69140,
       44688, 53608, 65896,  5966, 57391, 48248, 67410, 58671, 53781,
       77096, 12710, 77511, 29955, 28764, 78951, 53203, 55424, 63036,
        2084, 43083, 66692, 12173,  7825, 54046, 57018, 53150, 60625,
       17309,  7306,  3581, 40743, 45494,  3994,  8505, 33368,   194,
       79224,  8794, 50301,  3467, 73883, 66001, 79787, 15865, 41023,
       38009, 75670,  5119, 66146, 17522, 46056, 22407, 13265, 57820,
       53755, 33855, 55231, 69001, 67241, 25014, 65560, 69420, 17245,
       66440, 36626, 53314, 66841, 57385, 75208, 70967, 75095, 58551,
       72339, 52332,

In [70]:
ufosDS = ufos.loc[downSampleMask]

In [71]:
len(ufosDS)

1000

In [72]:
ufosDS

date                 city state country    shape  \
59616 2000-07-25 21:20:00             glendale    ca      us   circle   
23715 1965-12-09 16:48:00              enfield    ct      us   circle   
50133 2006-06-19 20:30:00          los angeles    ca      us    other   
18359 2006-12-15 01:00:00           green oaks    il      us   circle   
59487 2009-07-24 23:00:00              everett    wa      us    light   
...                   ...                  ...   ...     ...      ...   
38953 2014-04-24 23:45:00     naniamo (canada)    bc     NaN   circle   
4941  2011-10-27 19:30:00  east sooke (canada)    bc     NaN    light   
55695 2000-07-12 01:56:00             franklin    pa      us     disk   
57995 1999-07-19 05:00:00              durango    co      us  unknown   
7010  1999-10-08 21:00:00           munds park    az      us     cone   

       duration_seconds     duration  \
59616               5.0   5+ seconds   
23715             120.0    2 minutes   
50133             120.0  1-2 minutes   
18359               3.0    3 seconds   
59487             300.0        5 min   
...                 ...          ...   
38953               2.0    2 seconds   
4941              300.0      >5 min.   
55695            3600.0       1 hour   
57995             300.0       5 mins   
7010             2400.0      40+ min   

                                                 comment report_date  \
59616                     Bright&#44 Stoplight Red Craft  2001-08-05   
23715  Charting a UFO and identifying its points of o...  2008-08-12   
50133  I saw (starting from what seemed to be a 1/4 m...  2007-08-07   
18359  Bright circle of light at very high speeds and...  2007-02-01   
59487  I noticed 3 bright lights in the ski moving to...  2009-08-05   
...                                                  ...         ...   
38953  Green ufo seen over NE british columbia like a...  2014-05-02   
4941   Bright white/blue light moving in fluid manner...  2011-12-12   
55695                      Disc shaped object over NW Pa  2000-07-23   
57995  Hadn&#39t started to get light yet&#44 I was w...  1999-08-10   
7010   cone shaped mist with single white light at to...  2006-10-30   

        latitude   longitude  
59616  34.142500 -118.254167  
23715  41.976111  -72.592222  
50133  34.052222 -118.242778  
18359  42.290000  -87.903333  
59487  47.979167 -122.200833  
...          ...         ...  
38953  49.165884 -123.940065  
4941   48.366615 -123.706823  
55695  41.397778  -79.831667  
57995  37.275278 -107.879444  
7010   34.945556 -111.639444  

[1000 rows x 11 columns]

In [73]:
# 1. data = for a scatter plot is the downsampled data

# 2. scales
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

# 3. axis
x_ax = bqplot.Axis(scale=x_sc, label='Longitude')
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical', label='Latitude')

# 4. marks
scatters = bqplot.Scatter(x=ufosDS['longitude'], y=ufosDS['latitude'],
                         scales = {'x':x_sc, 'y':y_sc})

# skipping a bit... right into figure
fig = bqplot.Figure(marks=[scatters],axes=[x_ax, y_ax])
fig

Figure(axes=[Axis(label='Longitude', scale=LinearScale()), Axis(label='Latitude', orientation='vertical', scal…

In [76]:
# 1. data = for a scatter plot is the downsampled data

# 2. scales
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()
col_sc = bqplot.ColorScale()

# 3. axis
x_ax = bqplot.Axis(scale=x_sc, label='Longitude')
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical', label='Latitude')
col_ax = bqplot.ColorAxis(scale=col_sc, label='Duration in sec', orientation='vertical', side='right')

# 4. marks
scatters = bqplot.Scatter(x=ufosDS['longitude'], y=ufosDS['latitude'],
                          color = ufosDS['duration_seconds'],
                         scales = {'x':x_sc, 'y':y_sc, 'color':col_sc})

# skipping a bit... right into figure
fig = bqplot.Figure(marks=[scatters],axes=[x_ax, y_ax,col_ax])
fig

Figure(axes=[Axis(label='Longitude', scale=LinearScale()), Axis(label='Latitude', orientation='vertical', scal…

In [77]:
ufosDS['duration_seconds'].min(), ufosDS['duration_seconds'].max()

(0.5, 345600.0)

In [78]:
# 1. data = for a scatter plot is the downsampled data

# 2. scales
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()
col_sc = bqplot.ColorScale()

# 3. axis
x_ax = bqplot.Axis(scale=x_sc, label='Longitude')
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical', label='Latitude')
col_ax = bqplot.ColorAxis(scale=col_sc, label='Duration in sec', orientation='vertical', side='right')

# 4. marks
scatters = bqplot.Scatter(x=ufosDS['longitude'], y=ufosDS['latitude'],
                          color = np.log10(ufosDS['duration_seconds']),
                         scales = {'x':x_sc, 'y':y_sc, 'color':col_sc})

# skipping a bit... right into figure
fig = bqplot.Figure(marks=[scatters],axes=[x_ax, y_ax,col_ax])
fig

Figure(axes=[Axis(label='Longitude', scale=LinearScale()), Axis(label='Latitude', orientation='vertical', scal…

In [79]:
def generate_histogram_from_lat_long(ufos, nlong=20, nlat=20, longmin=-150, longmax=150,
                                     latmin=-40, latmax=70,
                                     takeLog=True):
    long_bins = np.linspace(longmin, longmax, nlong+1)
    lat_bins = np.linspace(latmin, latmax, nlat+1)
    hist2d, long_edges, lat_edges = np.histogram2d(ufos['longitude'], 
                                                   ufos['latitude'], 
                                                   weights=ufos['duration_seconds'],
                                                  bins = [long_bins,lat_bins])
    hist2d = hist2d.T
    if takeLog:
        hist2d[hist2d <= 0] = np.nan # set zeros to NaNs
        # then take log
        hist2d = np.log10(hist2d)
    long_centers = (long_edges[:-1] + long_edges[1:]) / 2
    lat_centers = (lat_edges[:-1] + lat_edges[1:]) / 2
    return hist2d, long_centers, lat_centers, long_edges, lat_edges

In [80]:
hist2d, long_centers, lat_centers, long_edges, lat_edges = generate_histogram_from_lat_long(ufos)

In [84]:
#hist2d

In [85]:
# 1. data for the UFOS lat/long map (pre-binned)

# 2. scales
col_sc = bqplot.ColorScale(scheme="RdPu", min=np.nanmin(hist2d), max=np.nanmax(hist2d))
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

# 3. axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc, label='Longitude')
y_ax = bqplot.Axis(scale=y_sc, label='Latitude', orientation='vertical')

# 4. marks
heat_map = bqplot.GridHeatMap(color=hist2d, row=lat_centers, column=long_centers,
                             scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'blue'})

# 5. interactivity

# all together now!
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(max=8.09710747658943, min=0.0, scheme='RdPu'),…

In [88]:
# 1. data for the UFOS lat/long map (pre-binned)

# 2. scales
col_sc = bqplot.ColorScale(scheme="RdPu", min=np.nanmin(hist2d), max=np.nanmax(hist2d))
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

# 3. axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc, label='Longitude')
y_ax = bqplot.Axis(scale=y_sc, label='Latitude', orientation='vertical')

# 4. marks
heat_map = bqplot.GridHeatMap(color=hist2d, row=lat_centers, column=long_centers,
                             scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'blue'})

# 5. interactivity
selectedLabel = ipywidgets.Label()
def get_data_value(change):
    if len(change['owner'].selected) == 1: # only 1 selection allowed
        i,j = change['owner'].selected[0]
        v = hist2d[i,j]
        selectedLabel.value = 'Total duration in log(sec)=' + str(v)
        
# make sure to link to the trait that is changing in the heat map
heat_map.observe(get_data_value, 'selected')

# all together now!
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
#fig
myDashboard = ipywidgets.VBox([selectedLabel, fig])
myDashboard

In [89]:
import datetime as dt

In [90]:
# 2. scales for scatter plot
x_scl = bqplot.DateScale(min=dt.datetime(1950,1,1),max=dt.datetime(2022,1,1))
y_scl = bqplot.LogScale()

In [91]:
ax_xcl = bqplot.Axis(label='Date', scale=x_scl)
ax_ycl = bqplot.Axis(label='Duration in Sec', scale=y_scl, orientation='vertical')

In [92]:
i,j = 19,0 # I know this has a lot of data!

In [94]:
# ufos[i,j] this won't work!  our data is not in a 20x20 grid format
long_min = long_edges[j] # j is associated with y
long_max = long_edges[j+1]

In [95]:
long_min, long_max

(-150.0, -135.0)

In [98]:
lat_min = lat_edges[i] # i is associated with x
lat_max = lat_edges[i+1]

In [99]:
lat_min, lat_max

(64.5, 70.0)

In [102]:
region_mask = ( (ufos['latitude']>=lat_min) & (ufos['latitude']<=lat_max) &\
              (ufos['longitude']>=long_min) & (ufos['longitude']<=long_max) )

In [103]:
ufos['latitude'][region_mask]

327      64.837778
2845     64.837778
3620     64.837778
4602     64.751111
6011     64.837778
           ...    
77347    64.751111
77497    64.837778
78571    64.837778
79029    64.837778
79470    64.837778
Name: latitude, Length: 74, dtype: float64

In [104]:
ufos['longitude'][region_mask]

327     -147.716389
2845    -147.716389
3620    -147.716389
4602    -147.349444
6011    -147.716389
            ...    
77347   -147.349444
77497   -147.716389
78571   -147.716389
79029   -147.716389
79470   -147.716389
Name: longitude, Length: 74, dtype: float64

In [105]:
# 4. Marks
scatters = bqplot.Scatter(x=ufos['date'][region_mask], 
                         y=ufos['duration_seconds'][region_mask],
                         scales={'x':x_scl, 'y':y_scl})

In [106]:
fig_dur = bqplot.Figure(marks=[scatters], axes=[ax_xcl, ax_ycl])
fig_dur

Figure(axes=[Axis(label='Date', scale=DateScale(max=datetime.datetime(2022, 1, 1, 0, 0), min=datetime.datetime…

In [107]:
# 1. data for the UFOS lat/long map (pre-binned)

# 2. scales
col_sc = bqplot.ColorScale(scheme="RdPu", min=np.nanmin(hist2d), max=np.nanmax(hist2d))
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

# 3. axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc, label='Longitude')
y_ax = bqplot.Axis(scale=y_sc, label='Latitude', orientation='vertical')

# 4. marks
heat_map = bqplot.GridHeatMap(color=hist2d, row=lat_centers, column=long_centers,
                             scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'blue'})

# all together now!
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
#fig
#myDashboard = ipywidgets.VBox([selectedLabel, fig])
#myDashboard

In [108]:
# 5. interactivity
selectedLabel = ipywidgets.Label()
def get_data_value(change):
    if len(change['owner'].selected) == 1: # only 1 selection allowed
        i,j = change['owner'].selected[0]
        v = hist2d[i,j]
        selectedLabel.value = 'Total duration in log(sec)=' + str(v)
        long_min = long_edges[j] # j is associated with y
        long_max = long_edges[j+1]
        lat_min = lat_edges[i] # i is associated with x
        lat_max = lat_edges[i+1]
        region_mask = ( (ufos['latitude']>=lat_min) & (ufos['latitude']<=lat_max) &\
              (ufos['longitude']>=long_min) & (ufos['longitude']<=long_max) )
        scatters.x = ufos['date'][region_mask]
        scatters.y = ufos['duration_seconds'][region_mask]
        
# make sure to link to the trait that is changing in the heat map
heat_map.observe(get_data_value, 'selected')

In [109]:
fig.layout.min_width='500px'
fig.layout.min_width='500px'

figures = ipywidgets.HBox([fig, fig_dur])

myDashboard = ipywidgets.VBox([selectedLabel, figures])
myDashboard

Updating the scatter plot to use a bar chart!

In [110]:
# bar plot

# scales
x_scl = bqplot.LinearScale()
y_scl = bqplot.LinearScale()

# axis
ax_xcl = bqplot.Axis(label='Year', scale=x_scl)
ax_ycl = bqplot.Axis(label='Total duration in sec', scale=y_scl, orientation='vertical')

In [111]:
i,j = 19,0 # I know this has a lot of data!
long_min = long_edges[j] # j is associated with y
long_max = long_edges[j+1]
lat_min = lat_edges[i] # i is associated with x
lat_max = lat_edges[i+1]
region_mask = ( (ufos['latitude']>=lat_min) & (ufos['latitude']<=lat_max) &\
              (ufos['longitude']>=long_min) & (ufos['longitude']<=long_max) )

In [112]:
ufos['year'] = ufos['date'].dt.year
ufos['year']

0        1949
1        1949
2        1955
3        1956
4        1960
         ... 
80327    2013
80328    2013
80329    2013
80330    2013
80331    2013
Name: year, Length: 80332, dtype: int64

In [113]:
dur, dur_edges = np.histogram(ufos['year'][region_mask], 
                             weights=ufos['duration_seconds'][region_mask],
                             bins=10)

In [114]:
dur_centers = (dur_edges[:-1]+dur_edges[1:])/2

In [115]:
# marks
dur_hist = bqplot.Bars(x=dur_centers, y=dur, scales={'x':x_scl, 'y':y_scl})

In [116]:
fig_dur = bqplot.Figure(marks=[dur_hist],axes=[ax_xcl,ax_ycl])

In [117]:
fig_dur

Figure(axes=[Axis(label='Year', scale=LinearScale(), side='bottom'), Axis(label='Total duration in sec', orien…

In [118]:
# 5. interactivity
selectedLabel = ipywidgets.Label()
def get_data_value(change):
    if len(change['owner'].selected) == 1: # only 1 selection allowed
        i,j = change['owner'].selected[0]
        v = hist2d[i,j]
        selectedLabel.value = 'Total duration in log(sec)=' + str(v)
        long_min = long_edges[j] # j is associated with y
        long_max = long_edges[j+1]
        lat_min = lat_edges[i] # i is associated with x
        lat_max = lat_edges[i+1]
        region_mask = ( (ufos['latitude']>=lat_min) & (ufos['latitude']<=lat_max) &\
              (ufos['longitude']>=long_min) & (ufos['longitude']<=long_max) )
        #scatters.x = ufos['date'][region_mask]
        #scatters.y = ufos['duration_seconds'][region_mask]
        if len(ufos['year'][region_mask])>0: # make sure we have data
            dur, dur_edges = np.histogram(ufos['year'][region_mask], 
                                         weights=ufos['duration_seconds'][region_mask],
                                         bins=10)     
            dur_centers = (dur_edges[:-1]+dur_edges[1:])/2
            dur_hist.x = dur_centers
            dur_hist.y = dur
            
# make sure to link to the trait that is changing in the heat map
heat_map.observe(get_data_value, 'selected')

In [120]:
# (I) GRIDHEAT MAP
# 1. data for the UFOS lat/long map (pre-binned)

# 2. scales
col_sc = bqplot.ColorScale(scheme="RdPu", min=np.nanmin(hist2d), max=np.nanmax(hist2d))
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

# 3. axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical', side='right')
x_ax = bqplot.Axis(scale=x_sc, label='Longitude')
y_ax = bqplot.Axis(scale=y_sc, label='Latitude', orientation='vertical')

# 4. marks
heat_map = bqplot.GridHeatMap(color=hist2d, row=lat_centers, column=long_centers,
                             scales={'color':col_sc, 'row':y_sc, 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'blue'})

# all together now!
fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])

In [121]:
# (II) BAR PLOT

# scales
x_scl = bqplot.LinearScale()
y_scl = bqplot.LinearScale()

# axis
ax_xcl = bqplot.Axis(label='Year', scale=x_scl)
ax_ycl = bqplot.Axis(label='Total duration in sec', scale=y_scl, orientation='vertical')

# marks/data
i,j = 19,0 # I know this has a lot of data!
long_min = long_edges[j] # j is associated with y
long_max = long_edges[j+1]
lat_min = lat_edges[i] # i is associated with x
lat_max = lat_edges[i+1]
region_mask = ( (ufos['latitude']>=lat_min) & (ufos['latitude']<=lat_max) &\
              (ufos['longitude']>=long_min) & (ufos['longitude']<=long_max) )

dur, dur_edges = np.histogram(ufos['year'][region_mask], 
                             weights=ufos['duration_seconds'][region_mask],
                             bins=10)

dur_hist = bqplot.Bars(x=dur_centers, y=dur, scales={'x':x_scl, 'y':y_scl})

fig_dur = bqplot.Figure(marks=[dur_hist],axes=[ax_xcl,ax_ycl])

In [122]:
# (III) LINKING GRIDHEATMAP TO BARPLOT
selectedLabel = ipywidgets.Label()
def get_data_value(change):
    if len(change['owner'].selected) == 1: # only 1 selection allowed
        i,j = change['owner'].selected[0]
        v = hist2d[i,j]
        selectedLabel.value = 'Total duration in log(sec)=' + str(v)
        long_min = long_edges[j] # j is associated with y
        long_max = long_edges[j+1]
        lat_min = lat_edges[i] # i is associated with x
        lat_max = lat_edges[i+1]
        region_mask = ( (ufos['latitude']>=lat_min) & (ufos['latitude']<=lat_max) &\
              (ufos['longitude']>=long_min) & (ufos['longitude']<=long_max) )
        if len(ufos['year'][region_mask])>0: # make sure we have data
            dur, dur_edges = np.histogram(ufos['year'][region_mask], 
                                         weights=ufos['duration_seconds'][region_mask],
                                         bins=10)     
            dur_centers = (dur_edges[:-1]+dur_edges[1:])/2
            dur_hist.x = dur_centers
            dur_hist.y = dur
            
# make sure to link to the trait that is changing in the heat map
heat_map.observe(get_data_value, 'selected')

In [123]:
# (IV) LAYOUT OF DASHBOARD
fig.layout.min_width='500px'
fig_dur.layout.min_width='500px'
figures = ipywidgets.HBox([fig, fig_dur])
myDashboard = ipywidgets.VBox([selectedLabel, figures])

In [124]:
myDashboard

## Homework hint!

One thing you might want to try for the homework is a pivot table.  Here is an example dataframe that is similiar in "shape" to the homework data:

In [125]:
df = pd.DataFrame({"A": ["foo", "foo", "foo", "foo", "foo",
                         "bar", "bar", "bar", "bar"],
                   "B": ["one", "one", "one", "two", "two",
                         "one", "one", "two", "two"],
                   "C": ["small", "large", "large", "small",
                         "small", "large", "small", "small",
                         "large"],
                   "D": [1, 2, 2, 3, 3, 4, 5, 6, 7],
                   "E": [2, 4, 5, 5, 6, 6, 8, 9, 9]})
df

A    B      C  D  E
0  foo  one  small  1  2
1  foo  one  large  2  4
2  foo  one  large  2  5
3  foo  two  small  3  5
4  foo  two  small  3  6
5  bar  one  large  4  6
6  bar  one  small  5  8
7  bar  two  small  6  9
8  bar  two  large  7  9

Let's say we want to sum all the values of "D" into bins of 'A' and 'C', we could do this with: